### ISSUE TITLE
Upgrade dependencies (security issues)

### ISSUE THREAD

**Issue by pegaltier** [carlossless/lokalise#10]
**It's needed to upgrade dependencies in order to get rid of many security issues like the following:**

   

>                                                                    
>   Moderate        Prototype Pollution                                           
>                                                                                 
>   Package         hoek                                                          
>                                                                                 
>   Dependency of   lokalise                                                      
>                                                                                 
>   Path            lokalise > request > hawk > hoek                              
>                                                                                 
>   More info       https://nodesecurity.io/advisories/566                        
>                                                                                 
> 
> 
>                                                                                 
>   Moderate        Prototype Pollution                                           
>                                                                                 
>   Package         hoek                                                          
>                                                                                 
>   Dependency of   lokalise                                                      
>                                                                                 
>   Path            lokalise > request > hawk > sntp > hoek                       
>                                                                                 
>   More info       https://nodesecurity.io/advisories/566                        
>                                                                                 
> 
> 
>                                                                                 
>   Moderate        Prototype Pollution                                           
>                                                                                 
>   Package         hoek                                                          
>                                                                                 
>   Dependency of   lokalise                                                      
>                                                                                 
>   Path            lokalise > request > hawk > boom > hoek                       
>                                                                                 
>   More info       https://nodesecurity.io/advisories/566                        
>                                                                                 
> 
> 
>                                                                                 
>   High            Regular Expression Denial of Service                          
>                                                                                 
>   Package         sshpk                                                         
>                                                                                 
>   Dependency of   lokalise                                                      
>                                                                                 
>   Path            lokalise > request > http-signature > sshpk                   
>                                                                                 
>   More info       https://nodesecurity.io/advisories/606                        
>                                                                                 
> 
> 
>                                                                                 
>   Moderate        Prototype Pollution                                           
>                                                                                 
>   Package         hoek                                                          
>                                                                                 
>   Dependency of   lokalise                                                      
>                                                                                 
>   Path            lokalise > request > hawk > cryptiles > boom > hoek           
>                                                                                 
>   More info       https://nodesecurity.io/advisories/566                        
>                                                                                 
> 
> 
>                                                                                 
>   Moderate        Out-of-bounds Read                                            
>                                                                                 
>   Package         stringstream                                                  
>                                                                                 
>   Dependency of   lokalise                                                      
>                                                                                 
>   Path            lokalise > request > stringstream                             
>                                                                                 
>   More info       https://nodesecurity.io/advisories/664

**Comment by carlossless** [comment]
Thanks for bringing this to my attention!

**Comment by carlossless** [comment]
#11 is merged. That should take care of this for now. Closing.
